#!/usr/bin/env python3

# get config variables
#print('config: %s' % config)
outdir = config['outdir']
raw_data = config['raw_data']
log_dir = config['log_dir']
flowcell = config['flowcell']
kit = config['kit']

# intermediate files
unzip_folder = os.path.join(outdir, 'unzipped_raw_data')
unzip_tmpfile = os.path.join(unzip_folder, 'tmp_file')
basecall_folder = os.path.join(outdir, 'basecalled/workspace')
basecall_tempfile = os.path.join(basecall_folder, 'tmp_file')
merged_folder = os.path.join(outdir, 'merged')
final_fq = os.path.join(merged_folder, 'merged.fq.gz')

# master rule
rule all:
    input:
        final_fq        

# unzip raw data to temp folder
rule unzip:
    input:
        raw_data
    output:
        temp(touch(unzip_tmpfile)),
        folder = temp(unzip_folder)
    log:
        os.path.join(log_dir, 'unzip.log')
    shell:
        'tar xvf {input} -C {output.folder} &> {log}'

# basecall
rule basecall:
    input:
        unzip_folder
    output:
        temp(touch(basecall_tempfile)),
        folder = basecall_folder
    shell:
        'printf "i:\t%s\no:\t%s\n" {input} {output.folder}'

# merge
rule merge:
    input:
        basecall_folder
    output:
        touch(final_fq)
    shell:
        'printf "i:\t%s\no:\t%s\n" {input} {output}'

