#!/usr/bin/env python3

import os

# get config variables
print('config: %s' % config)
outdir = config["other_output"]
input_files = config["other_input"]

# intermediate files
unzip_folder = os.path.join(outdir, 'unzipped_raw_data')
unzip_tmpfile = os.path.join(unzip_folder, 'tmp_file')
basecall_folder = os.path.join(outdir, 'basecalled')
merged_folder = os.path.join(outdir, 'merged')
final_fq = os.path.join(merged_folder, 'merged.fq.gz')

# master rule
rule all:
    input:
        final_fq        

# unzip raw data to temp folder
rule unzip:
    input:
        input_files
    output:
        temp(touch(unzip_tmpfile)),
        folder = unzip_folder
    shell:
        'tar xvf {input} -C {output.folder}'

# basecall
rule basecall:
    input:
        unzip_folder
    output:
        touch(basecall_folder)
    shell:
        'printf "i:\t%s\no:\t%s\n" {input} {output}'

# merge
rule merge:
    input:
        basecall_folder
    output:
        touch(final_fq)
    shell:
        'printf "i:\t%s\no:\t%s\n" {input} {output}'

