#!/usr/bin/env python3

# get config variables
#print('config: %s' % config)
outdir = config['outdir']
raw_data = config['raw_data']
log_dir = config['log_dir']
flowcell = config['flowcell']
kit = config['kit']

# intermediate files
unzip_folder = os.path.join(outdir, 'unzipped_raw_data')
unzip_tmpfile = os.path.join(unzip_folder, 'tmp_file')
basecall_folder = os.path.join(outdir, 'basecalled')
basecall_tempfile = os.path.join(basecall_folder, 'tmp_file')
merged_folder = os.path.join(outdir, 'merged')
temp_fq = os.path.join(merged_folder, 'tmp.fq')
final_fq = os.path.join(merged_folder, 'merged.fq.gz')

# master rule
rule all:
    input:
        final_fq        

# unzip raw data to temp folder
rule unzip:
    input:
        raw_data
    output:
        temp(touch(unzip_tmpfile)),
        folder = temp(unzip_folder)
    log:
        os.path.join(log_dir, 'unzip.log')
    shell:
        'tar xvf {input} -C {output.folder} &> {log}'

# basecall
rule basecall:
    input:
        unzip_folder
    output:
        temp(touch(basecall_tempfile)),
        folder=basecall_folder
    params:
        kit=kit,
        flowcell=flowcell
    threads:
        50
    shell:
        'read_fast5_basecaller.py '
        '--worker_threads {threads} '
        '--input {input} '
        '--save_path {output.folder} '
        '--flowcell {params.flowcell} '
        '--kit {params.kit} '
        '--recursive '
        '--output_format fastq '

# merge
rule merge:
    input:
        basecall_folder
    output:
        temp(temp_fq)
    shell:
        'cat {input}/workspace/*.fastq | '
        'sed -e \'/^[[:space:]]*$/d\' > '
        '{output}'

# reformat
rule reformat:
    input:
        temp_fq
    output:
        final_fq
    shell:
        'reformat.sh '
        'in={input} '
        'interleaved=f '
        'out={input} '
        'zl=9 '
        'bhist={merged_folder}/bhist.txt '
        'qhist={merged_folder}/qhist.txt ' 
        'qchist={merged_folder}/qchist.txt ' 
        'aqhist={merged_folder}/aqhist.txt '
        'bqhist={merged_folder}/bqhist.txt '
        'lhist={merged_folder}/lhist.txt '
        'gchist={merged_folder}/gchist.txt ' 
        'gcbins=auto'
