#!/usr/bin/env bash

set -eu

input_files=( 
    20170621_0344_ASW_12_05X_SPRI.tar.gz
    20170622_2306_ASW12_04xSPRI_20170623.tar.gz
    20170621_0351_ASW_12_05X_SPRI.tar.gz
    20170622_2313_ASW12_04xSPRI_20170623.tar.gz
 )

outdir="output/basecalled"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# extract files to temporary directory
tmpdir="$(TMPDIR="${outdir}" mktemp --directory)"
for tarfile in "${input_files[@]}"; do
    tar xvf "${tarfile}" -C "${tmpdir}" 
done

# set up files
log_file="${outdir}/albacore.log"
err_file="${outdir}/albacore.err"

# basecall from temporary directory
read_fast5_basecaller.py --worker_threads 50 \
    --input "${tmpdir}" \
    --save_path "${outdir}" \
    --flowcell "FLO-MIN107" \
    --kit "SQK-RAD002" \
    --recursive \
    --output_format fastq \
    > "${log_file}" \
    &> "${err_file}"

# tidy up temp files
rm -r "${tmpdir}"
