#!/usr/bin/env bash

set -eu

input_files=( 
    data/20170819_0106__0113_LUG8.tar.gz
 )

outdir="output/basecalled"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# extract files to temporary directory
tmpdir="$(mktemp --directory -p "${outdir}")"
printf "[ %s: Extracting raw data ]\ntmpdir:\t%s\n" \
    "$(date)" "${tmpdir}"
for tarfile in "${input_files[@]}"; do
    printf "%s\n" "${tarfile}"
    tar xvf "${tarfile}" -C "${tmpdir}" 
done

# set up files
log_file="${outdir}/albacore.log"
err_file="${outdir}/albacore.err"

# basecall from temporary directory
printf "[ %s: Calling read_fast5_basecaller.py ]\noutdir:\t%s\n" \
    "$(date)" "${outdir}"

read_fast5_basecaller.py --worker_threads 50 \
    --input "${tmpdir}" \
    --save_path "${outdir}" \
    --flowcell "FLO-MIN106" \
    --kit "SQK-RAD003" \
    --recursive \
    --output_format fastq \
    > "${log_file}" \
    &> "${err_file}"

# tidy up temp files
printf "[ %s: Removing tempfiles ]\n" "$(date)"
rm -r "${tmpdir}"
