#!/usr/bin/env bash

set -eu

input="output/basecalled/workspace"
outdir="output/basecalled/merged"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# intermediate files
tmp_file="${outdir}/tmp.fastq"
f_file="${outdir}/f.fastq"
log_file="${outdir}/reformat.log"

# put all the reads in the same file
cat "${input}"/*.fastq > "${tmp_file}"

# remove blank lines
sed -e '/^[[:space:]]*$/d' "${tmp_file}" > "${f_file}"

# compress and get stats with bbmap
bin/bbmap/reformat.sh \
    "in=${f_file}" \
    interleaved=f \
    "out=${outdir}/merged.fq.gz" \
    zl=9 \
    "bhist=${outdir}/bhist.txt" \
    "qhist=${outdir}/qhist.txt" \
    "qchist=${outdir}/qchist.txt" \
    "aqhist=${outdir}/aqhist.txt" \
    "bqhist=${outdir}/bqhist.txt" \
    "lhist=${outdir}/lhist.txt" \
    "gchist=${outdir}/gchist.txt" \
    gcbins=auto \
    2> "${log_file}"

# tidy up
rm "${tmp_file}" "${f_file}"
