#!/usr/bin/env bash

set -eu

INPUT="data/raw/tmp/20170621_0351_ASW_12_05X_SPRI"

outdir="output/20170621_0351_ASW_12_05X_SPRI_partial"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

log_file="${outdir}/albacore.log"
err_file="${outdir}/albacore.err"

read_fast5_basecaller.py --worker_threads 50 \
    --input "${INPUT}" \
    --save_path "${outdir}" \
    --flowcell "FLO-MIN107" \
    --kit "SQK-RAD002" \
    --recursive \
    --output_format fastq \
    > "${log_file}" \
    &> "${err_file}"
